// <auto-generated />
using Empresa.ProdutosApi.Infra.Data.ORM.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Empresa.ProdutosApi.Infra.Data.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    [Migration("20220412224353_Add.Empresa.ProdutosApi.Produto")]
    partial class AddEmpresaProdutosApiProduto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Empresa.ProdutosApi.Domains.Entities.Produto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("produto_id")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("produto")
                        .HasColumnType("VarChar(80)");

                    b.Property<decimal>("Preco")
                        .HasColumnName("preco")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
